- pipeline: ci
  name: CI
  events:
  - type: WEBHOOK
    totp: true
  artifacts:
  - '*'
  actions:
  - action: npm test
    type: BUILD
    commands: |-
      # yarn install
      npm install
      npm test
    shell: BASH
    docker_image_name: library/node
    docker_image_tag: 24
